---
title: "MT5763_1_200030711"
author: "Alexander Curtis"
date: "03/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries:
```{r, message = FALSE}
library(tidyverse)
library(lubridate)
library(gridExtra)
```

## Data wrangling

Data wrangling for the Seoul dataset:
```{r}
BikeSeoul <- read.csv("BikeSeoul.csv") %>% 
  # Remove unwanted columns
  select(-Visibility..10m.,
         -Dew.point.temperature.C.,
         -Solar.Radiation..MJ.m2., -Rainfall.mm.,
         -Snowfall..cm.) %>%
  # Keep only functioning days then remove column
  filter(Functioning.Day == "Yes") %>%
  select(-Functioning.Day) %>%
  rename(Count = Rented.Bike.Count, 
         Temperature = Temperature.C.,
         Humidity = Humidity...,
         WindSpeed = Wind.speed..m.s.,
         Season = Seasons) %>%
  mutate(Date = as.Date(Date, "%d/%m/%Y")) %>%
  mutate(FullDate = make_datetime(year = year(Date),
                                  month = month(Date),
                                  day = day(Date),
                                  hour = Hour)) %>%
  mutate(Holiday = factor(Holiday, 
                          levels = c("Holiday", "No Holiday"),
                          labels = c("Yes", "No"),
                          ordered = TRUE)) %>%
  mutate(Season = factor(Season, 
                         levels = c("Spring", "Summer", "Autumn", "Winter"),
                         ordered = TRUE))
```


Data wrangling for the Washington DC dataset:
```{r}
BikeWashingtonDC <- read.csv("BikeWashingtonDC.csv") %>%
  # Remove unwanted columns
  select(-instant,
         -yr,
         -mnth,
         -weekday,
         -workingday,
         -weathersit,
         -atemp,
         -casual,
         -registered) %>%
  rename(Date = dteday,
         Season = season,
         Hour = hr,
         Holiday = holiday,
         Temperature = temp,
         Humidity = hum,
         Windspeed = windspeed,
         Count = cnt) %>%
  # Transform humidity into a percentage
  mutate(Humidity = Humidity * 100) %>%
  # Transform Temperature into degrees Celcius
  mutate(Temperature = 47 * Temperature - 8) %>%
  # Transform Windspeed into m/s
  mutate(Windspeed = Windspeed * 67) %>%
  mutate(Season = factor(Season,
                         levels = c(2, 3, 4, 1),
                         labels = c("Spring", "Summer", "Autumn", "Winter"),
                         ordered = TRUE)) %>%
  mutate(Holiday = factor(Holiday,
                          levels = c(1, 0),
                          labels = c("Yes", "No"),
                          ordered = TRUE)) %>%
  mutate(Date = as.Date(Date, "%Y-%m-%d")) %>%
  mutate(FullDate = make_datetime(year = year(Date),
                                  month = month(Date),
                                  day = day(Date),
                                  hour = Hour))
```


## Data Visualisation

### How does air temperature vary over the course of a year?

```{r, message = FALSE}
BikeSeoul %>% 
  group_by(Date) %>%
  summarise(DailyMean = mean(Temperature)) %>%
  ggplot() +
  geom_line(aes(x = Date, y = DailyMean)) +
  ylab("Temperature (ºC)") +
  ggtitle("Mean Daily Air Temperature in Seoul")
```

```{r, message = FALSE}
BikeWashingtonDC %>% 
  filter(year(Date) == 2011) %>%
  group_by(Date) %>%
  summarise(DailyMean = mean(Temperature)) %>%
  ggplot() +
  geom_line(aes(x = Date, y = DailyMean)) +
  ylab("Temperature (ºC)") +
  ggtitle("Mean Daily Air Temperature in Washington DC (2011)")
```

### Do seasons affect the average number of rented bikes?

```{r, message = FALSE}
p1 <- BikeSeoul %>%
  group_by(Season) %>%
  summarise(meanCount = mean(Count)) %>%
  ggplot() + 
  geom_col(aes(x = Season, y = meanCount)) + 
  ylab("Count") +
  ggtitle("Seoul")
p2 <- BikeWashingtonDC %>%
  group_by(Season) %>%
  summarise(meanCount = mean(Count)) %>%
  ggplot() + 
  geom_col(aes(x = Season, y = meanCount)) + 
  ylab("Count") +
  ggtitle("Washington DC")
grid.arrange(p1, p2, ncol = 2, top = "Average Hourly Bike Rental")
```

### Do holidays increase or decrease the demand for rented bikes?

```{r}
p1 <- ggplot(BikeSeoul) +
  geom_boxplot(aes(x = Holiday, y = Count))
p2 <- ggplot(BikeWashingtonDC) +
  geom_boxplot(aes(x = Holiday, y = Count))
grid.arrange(p1, p2, ncol = 2)
```












